backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"      # Path used in the site

media_library:
  name: uploadcare # or 'cloudinary', or omit for default

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }